name: ${project.name}
main: studio.magemonkey.homestead.Homestead
version: ${project.version}
depend: [ CodexCore, Sapphire, WorldGuard, Vault ]
authors: [ Travja, GotoFinal ]
api-version: 1.13

commands:
  #plot:
  house:
    usage: /<command>
    description: Plots commands
  system:
    usage: /<command>
    description: Controls entire plugin